### PR TITLE
Fix quest Kodo Roundup

### PR DESCRIPTION
**Pull request by ghost**
You could simply talk to the kodo before and get credits instantly, now you need to go to smeeds, he will inspect the kodo and then you will get the credits.

This fix was made for an older revision of MaNGOS so please test it before merging thanks.

---
This change is [Reviewable](https://reviewable.io/reviews/mangos/scriptdev3/69)

### CODE REVIEW

**Comment by ghost** [comment]
I stand corrected, M0 seems to not have a check. Will test your code out :)
------Before update
M1 auto complete as soon as you get near.
M2 works with current code

**Comment by ghost** [comment]
TRIGGERED_OLD_TRIGGERED

^  Causes build fail

**Comment by ghost** [comment]
On current mangos : https://streamable.com/9zkse

With my fix : https://streamable.com/vu1bg

Fixed build

edit : the problem was you could talk to the kodo and get credits also m_creature->GetMotionMaster()->MoveIdle(); was needed because the kodo would still move after being inspected also and I removed uneeded check and make simple condition instead

**Comment by ghost** [comment]
Nice, some Pros / Cons
**M0**
Pro: This fixes the issue of being able to use gossip to get credit anywhere.
Con: You are still able to interact with the kodo as if it had gossip.  Message: greeting <player name>.

**M1**
Pro: None
Con: Credit count is still automatic the moment you get near a Kodo

**M2**
Pro: Still works great.
Con: None

**Nice job so far. Thanks for providing what you have to this point**

**Comment by ghost** [comment]
Hey, I only develop on vanilla I can't test other version sorry.

I fixed all reaming issue on M0, and provided all SQL files [here](https://github.com/mangos/ScriptDev3/pull/69/commits/1e32c971f31dfb1bc59bd7b1565c319bafc70d28) I consider my PR finished (i'm not sure why the same code doesn't work on all version)

Proof of it working on M0 https://streamable.com/r45c8

**Comment by MadMaxMangos** [comment]
Nice work, @Necrovoice will take a look at this later 👍

**Comment by MadMaxMangos** [comment]
@Inifield if you want a copy of tbc or wrath i can provide that, message me via the getmangos.eu website if you want copies.

**Comment by ghost** [comment]
@MadMaxMangos i'm kind of busy with vanilla, so much to do and so little time

**Comment by MadMaxMangos** [comment]
@Inifield know the feeling, no worries.

**Comment by billy1arm** [comment]
@Inifield @Necrovoice - For future reference you can use the 'core defined directives' to isolate code for certain core(s)...

Take a quick look at:
https://github.com/mangos/ScriptDev3/blob/master/include/sc_creature.cpp#L723

Which is a good example

**Pull request merged**
